version: 2
jobs:
  build:
    working_directory: /build
    branches:
      only:
        - source
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get -y install git rsync python-dev graphviz libgraphviz-dev pkg-config
            pip install --user -r https://raw.githubusercontent.com/FCP-INDI/C-PAC/master/requirements.txt
            pip install --user git+https://github.com/FCP-INDI/C-PAC.git
            pip install --user sphinx
            pip install --user numpydoc
            pip install --user PyGithub
            pip install --user sphinxcontrib-programoutput
            git clone https://github.com/FCP-INDI/C-PAC.git
      - run:
          name: Build docs
          command: |
            ./bin/build

      - run:
          name: Configure git user
          command: |
            git config --global user.email "ci-build@fcp-indi.github.com"
            git config --global user.name "ci-build"
      - run:
          name: Deploy docs
          command: |
            export GITMESSAGE=`git log -1 --oneline --pretty=%s`
            git clone --single-branch --branch master git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git /tmp/repo
            rsync -rtv ./ /tmp/repo/ --exclude '.git'
            cd /tmp/repo
            git rm -f .gitignore || rm -f .gitignore || true
            git add .
            git rm -fr docs/developer/_sources || rm -f docs/developer/_sources || true
            git rm -fr docs/developer/.doctrees || rm -f docs/developer/.doctrees || true
            git rm -fr docs/user/_sources || rm -f docs/user/_sources || true
            git rm -fr docs/user/.doctrees || rm -f docs/user/.doctrees || true
            git commit -m "${GITMESSAGE}" --allow-empty
            git push -f origin master
            cd -
